### ISSUE TITLE
Cannot pass token to npm script anymore

### ISSUE THREAD

**Issue by wintercounter** [conventional-changelog/releaser-tools#187]
This started to happen with the recent updates. Until now this was working fine:

```
// package.json
{
    "scripts": {
        "release": "conventional-github-releaser -t"
    }
}

npm run release -- MY_TOKEN
```

But I started to get the following error:

```
C:\...es\conventional-github-releaser\node_modules\meow\node_modules\minimist-options\index.js:101
                                        throw new TypeError(`Expected "${key}" default value to be of type "${expectedType}", got ${prettyPrint(defaultType)}`);
                                        ^

TypeError: Expected "token" default value to be of type "string", got "undefined"
    at C:\node_modules\conventional-github-releaser\node_modules\meow\node_modules\minimist-options\index.js:101:12
    at Array.forEach (<anonymous>)
    at buildOptions (C:\node_modules\conventional-github-releaser\node_modules\meow\node_modules\minimist-options\index.js:64:23)
    at meow (C:\node_modules\conventional-github-releaser\node_modules\meow\index.js:136:18)
    at Object.<anonymous> (C:\node_modules\conventional-github-releaser\src\cli.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

```

**Comment by cookiescrumbs** [comment]
I'm getting the same. I've locked to v3.1.3.

**Comment by Hartorn** [comment]
We cannot even run in cli `conventional-github-releaser --help`, it breaks also with the same message

**Comment by thesmiley1** [comment]
I'm not sure about previous behavior, but I was able to work around the issue by supplying a `CONVENTIONAL_GITLAB_RELEASER_TOKEN` environment variable, even just a dummy one to get the help working, e.g.:

`CONVENTIONAL_GITLAB_RELEASER_TOKEN=asdf conventional-gitlab-releaser --help`

Obviously there is still a bug, though: it shouldn't take a dummy token to print the help documentation.

**Comment by carmanchris31** [comment]
Updating https://github.com/conventional-changelog/releaser-tools/blob/master/packages/conventional-github-releaser/src/cli.js#L50 should fix this:

```diff
-       default: process.env.CONVENTIONAL_GITHUB_RELEASER_TOKEN,
+       default: process.env.CONVENTIONAL_GITHUB_RELEASER_TOKEN || '',
```

**Comment by lvjiaxuan** [comment]
v3.1.5 still error.
