### ISSUE TITLE
Error from minimist-options: TypeError: Expected "token" default value to be of type "string", got "undefined"

### ISSUE THREAD

**Issue by plasticrake** [conventional-changelog/releaser-tools#190]
See below for output when trying to run from fresh install.

May be related to #184.

```
$ npm install -g conventional-github-releaser
...
+ conventional-github-releaser@3.1.5
...
$ conventional-github-releaser       
/usr/local/lib/node_modules/conventional-github-releaser/node_modules/minimist-options/index.js:101
                                        throw new TypeError(`Expected "${key}" default value to be of type "${expectedType}", got ${prettyPrint(defaultType)}`);
                                        ^

TypeError: Expected "token" default value to be of type "string", got "undefined"
    at /usr/local/lib/node_modules/conventional-github-releaser/node_modules/minimist-options/index.js:101:12
    at Array.forEach (<anonymous>)
    at buildOptions (/usr/local/lib/node_modules/conventional-github-releaser/node_modules/minimist-options/index.js:64:23)
    at meow (/usr/local/lib/node_modules/conventional-github-releaser/node_modules/meow/index.js:125:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/conventional-github-releaser/src/cli.js:9:13)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)

```

**Comment by tw0517tw** [comment]
seems a duplicate to #187 
pending PR #189 should fix this

**Comment by jsakas** [comment]
Here is a workaround until someone gets around to merging that PR.

```
CONVENTIONAL_GITHUB_RELEASER_TOKEN=xxxxx conventional-github-releaser -p angular -r 1 -v
```
