### ISSUE TITLE
conventional-github-releaser 3.1.2 issue

### ISSUE THREAD

**Issue by AlecRust** [conventional-changelog/releaser-tools#93]
In `conventional-github-releaser` versions below 3.1.2 my `gulp release` script works correctly:

```js
function createRelease(done) {
  githubReleaser(
    {
      type: 'oauth',
      token: process.env.CONVENTIONAL_GITHUB_RELEASER_TOKEN
    },
    done
  )
}
```

With version 3.1.2 though  I get:

```sh
[18:58:56] Starting 'createRelease'...
[18:58:56] 'createRelease' errored after 255 ms
[18:58:56] RequestError: getaddrinfo ENOTFOUND undefinedrepos undefinedrepos:443
    at ClientRequest.req.once.err (/Users/alec/projects/my-site/node_modules/got/index.js:182:22)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:180:13)
    at ClientRequest.emit (domain.js:421:20)
    at TLSSocket.socketErrorListener (_http_client.js:395:9)
    at TLSSocket.emit (events.js:180:13)
    at TLSSocket.emit (domain.js:421:20)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:114:19)
[18:58:56] 'release' errored after 5.73 s
```

**Comment by hutson** [comment]
@AlecRust thank you for reporting this issue.

@tinesoft thank you for diving into this issue and providing an explanation as to the cause.

I'm not sure when I'll have the time to address this issue in the GitHub releaser, so I've marked the issue as `help wanted` in hopes the community is able and willing to contribute a fix sooner.
